blank_issues_enabled: true
contact_links:
  - name: Oggy Support
    url : https://t.me/+mjjx41G5CKM4ZjVl
    about: Direct chat on non-inquiries subjects.
  - name: Documentation
    
    about: Documentation for getting started with bot.
