blank_issues_enabled: true
contact_links:
  - name: Oggy Support
    
    about: Direct chat on non-inquiries subjects.
  - name: Documentation
    
    about: Documentation for getting started with bot.
